const PDFDocument = require("pdfkit");

const money = (v) => `Rs. ${Number(v || 0).toLocaleString()}`;

// Mirrors the field set shown in frontend/src/components/InstallmentReceiptPrint.jsx,
// laid out with pdfkit instead of html2pdf since production runs on Vercel serverless
// (no headless-Chrome-friendly filesystem for Puppeteer).
const generateInstallmentReceiptPdf = ({
  installment,
  sale,
  customer,
  allInstallments = [],
  payment = null,
}) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const amountReceivedNow = payment
      ? Number(payment.totalPaid || 0)
      : Number(installment.paidAmount || 0);

    const totalPaidTillNow = allInstallments.reduce(
      (sum, i) => sum + Number(i.paidAmount || 0),
      0
    );

    const paidInstallments = allInstallments.filter(
      (i) => i.status === "paid"
    ).length;
    const pendingInstallments = allInstallments.filter(
      (i) => i.status !== "paid"
    ).length;

    // Header
    doc
      .fontSize(20)
      .fillColor("#8a6d1a")
      .text("Master Electronics", { continued: false });
    doc.fontSize(11).fillColor("#555").text("Installment Payment Receipt");
    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#000")
      .text(`Receipt: RCP-${installment.id}`, { align: "right" })
      .text(`Date: ${installment.paidDate || "-"}`, { align: "right" });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke();
    doc.moveDown(1);

    // Invoice / customer
    doc.fontSize(11).fillColor("#000");
    doc.text(`Invoice: ${sale?.invoiceNo || installment.saleId}`);
    doc.text(`Installment #${installment.installmentNo}`);
    doc.moveDown(0.5);
    doc.text(`Customer: ${customer?.name || "-"}`);
    doc.text(`Phone: ${customer?.phone || "-"}`);

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ccc").stroke();
    doc.moveDown(1);

    // Item / sale details
    doc.fontSize(12).fillColor("#8a6d1a").text("Item / Sale Details");
    doc.fontSize(10).fillColor("#000");
    doc.text(`Product: ${sale?.product?.productName || "-"}`);
    doc.text(`Sale Type: ${sale?.saleType || "installment"}`);
    doc.text(`Total Item Price: ${money(sale?.finalAmount)}`);
    doc.text(
      `Total Paid Till Now: ${money(totalPaidTillNow || sale?.paidAmount)}`
    );
    doc.text(`Total Remaining: ${money(sale?.remainingAmount)}`);
    doc.text(`Status: ${sale?.status || "-"}`);

    doc.moveDown(1);

    // Payment table
    const rows = [
      ["Current Installment Amount", money(installment.amount)],
      ["Total Amount Received", money(amountReceivedNow)],
      [
        "Fine Paid",
        money(payment ? payment.finePaid : installment.finePaid),
      ],
      ["Fine Discount", money(installment.fineDiscount)],
      ["Remaining of This Installment", money(installment.remainingAmount)],
    ];

    if (payment?.reamortized) {
      rows.push([
        `Extra ${money(payment.excessAmount)} Applied Ahead`,
        `Reduced next ${payment.futureCount} installment(s)`,
      ]);
    }

    rows.push(
      ["Paid Installments", String(paidInstallments)],
      ["Pending Installments", String(pendingInstallments)],
      ["Due Date", installment.dueDate]
    );

    const colWidth = 495;
    const labelWidth = 320;

    rows.forEach(([label, value]) => {
      const rowTop = doc.y;
      doc.rect(50, rowTop, colWidth, 22).strokeColor("#ddd").stroke();
      doc
        .fontSize(10)
        .fillColor("#333")
        .text(label, 58, rowTop + 6, { width: labelWidth - 16 });
      doc.text(value, 50 + labelWidth, rowTop + 6, {
        width: colWidth - labelWidth - 10,
        align: "right",
      });
      doc.y = rowTop + 22;
    });

    doc.moveDown(1.5);

    // Notes
    const notes =
      installment.installmentNo === 1
        ? "Advance received as first installment."
        : installment.notes || "-";
    doc.fontSize(10).fillColor("#000").text(`Notes: ${notes}`);

    doc.moveDown(3);
    doc
      .fontSize(9)
      .fillColor("#888")
      .text("This receipt is generated by Master Electronics system.", {
        align: "center",
      });

    doc.end();
  });
};

module.exports = { generateInstallmentReceiptPdf };
