const money = (v) => Number(v || 0).toLocaleString();

const statusLabel = (status) => {
  if (status === "paid") return "Paid";
  if (status === "overdue") return "Overdue";
  if (status === "partial") return "Partial";
  return "Pending";
};

const DueThisMonthPrint = ({ month, summary, installments = [] }) => {
  const monthLabel = (() => {
    const [year, mon] = String(month || "").split("-");
    if (!year || !mon) return month;
    const date = new Date(Number(year), Number(mon) - 1, 1);
    return date.toLocaleDateString("en-US", { month: "long", year: "numeric" });
  })();

  return (
    <div
      id="due-this-month-print"
      className="invoice-root bg-[#050505] text-white p-8 w-full rounded-[32px] border border-yellow-500/20 shadow-[0_20px_80px_rgba(0,0,0,0.35)]"
    >
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6 mb-8 header-card">
        <div>
          <img src="/logo.png" className="h-20 mb-4" />
          <h1 className="text-3xl font-bold text-yellow-400">Master Electronics</h1>
          <p className="text-gray-400 mt-1">Installments Due — {monthLabel}</p>
        </div>

        <div className="rounded-3xl border border-yellow-500/20 bg-yellow-500/10 px-6 py-4 text-right">
          <p className="text-xs uppercase tracking-[0.2em] text-yellow-300 font-semibold">
            Summary
          </p>
          <p className="text-sm text-gray-300 mt-2">
            Total: {summary?.totalItems || 0} | Paid: {summary?.paidCount || 0} | Unpaid:{" "}
            {summary?.unpaidCount || 0}
          </p>
          <p className="text-sm text-gray-300 mt-1">
            Rs. {money(summary?.totalCollected)} collected of Rs.{" "}
            {money(summary?.totalAmount)}
          </p>
        </div>
      </div>

      <div className="section-card">
        <table className="w-full border-separate border-spacing-0">
          <thead>
            <tr className="text-gray-300">
              <th className="border border-[#2b2b34] px-3 py-2 text-left">#</th>
              <th className="border border-[#2b2b34] px-3 py-2 text-left">Customer</th>
              <th className="border border-[#2b2b34] px-3 py-2 text-left">Contact</th>
              <th className="border border-[#2b2b34] px-3 py-2 text-left">Product</th>
              <th className="border border-[#2b2b34] px-3 py-2 text-left">Due Date</th>
              <th className="border border-[#2b2b34] px-3 py-2 text-right">Amount</th>
              <th className="border border-[#2b2b34] px-3 py-2 text-left">Status</th>
            </tr>
          </thead>

          <tbody>
            {installments.map((item, index) => (
              <tr key={item.id} className="text-gray-300">
                <td className="border border-[#2b2b34] px-3 py-2">{index + 1}</td>
                <td className="border border-[#2b2b34] px-3 py-2 font-semibold text-white">
                  {item.customerName}
                </td>
                <td className="border border-[#2b2b34] px-3 py-2">{item.customerPhone}</td>
                <td className="border border-[#2b2b34] px-3 py-2">{item.productName}</td>
                <td className="border border-[#2b2b34] px-3 py-2">{item.dueDate}</td>
                <td className="border border-[#2b2b34] px-3 py-2 text-right">
                  Rs. {money(item.amount)}
                </td>
                <td className="border border-[#2b2b34] px-3 py-2">
                  {statusLabel(item.displayStatus)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="text-center text-xs mt-8 text-gray-500">
        Generated by Master Electronics system.
      </p>
    </div>
  );
};

export default DueThisMonthPrint;
