const money = (v) => Number(v || 0).toLocaleString();

const InstallmentReceiptPrint = ({ installment, sale, installments = [] }) => {
  if (!installment) return null;

  const totalPaidTillNow = installments.reduce(
    (sum, i) => sum + Number(i.paidAmount || 0),
    0
  );

  const pendingInstallments = installments.filter(
    (i) => i.status !== "paid"
  ).length;

  const paidInstallments = installments.filter(
    (i) => i.status === "paid"
  ).length;

  return (
    <div
      id={`receipt-print-${installment.id}`}
      className="bg-white text-black p-8 w-full"
    >
      <div className="border-b-4 border-yellow-500 pb-4 mb-6 text-center">
        <img src="/logo.png" className="h-20 mx-auto mb-2" />
        <h1 className="text-3xl font-bold">Master Electronics</h1>
        <p className="text-sm">Installment Payment Receipt</p>
      </div>

      <div className="grid grid-cols-2 gap-3 text-sm mb-6">
        <p><b>Receipt No:</b> RCP-{installment.id}</p>
        <p><b>Receipt Date:</b> {installment.paidDate || "-"}</p>
        <p><b>Invoice No:</b> {sale?.invoiceNo || installment.saleId}</p>
        <p><b>Installment No:</b> #{installment.installmentNo}</p>
      </div>

      <div className="border rounded-lg p-4 mb-5">
        <h2 className="font-bold mb-3">Customer Details</h2>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <p><b>Name:</b> {installment.customer?.name || sale?.customer?.name || "-"}</p>
          <p><b>Phone:</b> {installment.customer?.phone || sale?.customer?.phone || "-"}</p>
          <p><b>CNIC:</b> {installment.customer?.cnic || sale?.customer?.cnic || "-"}</p>
          <p><b>Address:</b> {installment.customer?.address || sale?.customer?.address || "-"}</p>
        </div>
      </div>

      <div className="border rounded-lg p-4 mb-5">
        <h2 className="font-bold mb-3">Item / Sale Details</h2>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <p><b>Product:</b> {sale?.product?.productName || "-"}</p>
          <p><b>Sale Type:</b> {sale?.saleType || "installment"}</p>
          <p><b>Total Item Price:</b> Rs. {money(sale?.finalAmount)}</p>
          <p><b>Total Paid Till Now:</b> Rs. {money(totalPaidTillNow || sale?.paidAmount)}</p>
          <p><b>Total Remaining:</b> Rs. {money(sale?.remainingAmount)}</p>
          <p><b>Status:</b> {sale?.status || "-"}</p>
        </div>
      </div>

      <table className="w-full border-collapse text-sm mb-5">
        <tbody>
          <tr>
            <td className="border p-2 font-bold">Current Installment Amount</td>
            <td className="border p-2">Rs. {money(installment.amount)}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Amount Paid in This Receipt</td>
            <td className="border p-2">Rs. {money(installment.paidAmount)}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Fine Paid</td>
            <td className="border p-2">Rs. {money(installment.finePaid)}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Fine Discount</td>
            <td className="border p-2">Rs. {money(installment.fineDiscount)}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Remaining of This Installment</td>
            <td className="border p-2">Rs. {money(installment.remainingAmount)}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Paid Installments</td>
            <td className="border p-2">{paidInstallments}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Pending Installments</td>
            <td className="border p-2">{pendingInstallments}</td>
          </tr>
          <tr>
            <td className="border p-2 font-bold">Due Date</td>
            <td className="border p-2">{installment.dueDate}</td>
          </tr>
        </tbody>
      </table>

      <p className="text-sm mb-10">
        <b>Notes:</b>{" "}
        {installment.installmentNo === 1
          ? "Advance received as first installment."
          : installment.notes || "-"}
      </p>

      <div className="grid grid-cols-2 gap-12 text-center text-sm mt-16">
        <div className="border-t pt-2">Customer Signature</div>
        <div className="border-t pt-2">Receiver Signature</div>
      </div>

      <p className="text-center text-xs mt-8">
        This receipt is generated by Master Electronics system.
      </p>
    </div>
  );
};

export default InstallmentReceiptPrint;